Botaoajuste
rafaballerini/ReactTypescriptCurso pull request #4
Opened 2021-07-14 13:06 UTC by rafaballerini

Ajuste do botão, referente a solicitação: 

A App tem um comportamento “diferente” ao clicar várias vezes no botão “começar” mas acredito que seja por não está finalizado ainda.

2021-07-14 22:02 UTC, bugan commented on projeto/src/pages/App.tsx
> +    }, 1000)
Essa função toda poderia estar no componente Cronometro. Nada dela tem relação com os outros componentes

2021-07-14 22:02 UTC, bugan commented on projeto/src/pages/App.tsx
>      </div>
No geral o código não ta muito compreensível, vale pensarmos em nomes mais descritivos na hora de traduzir o código.

2021-07-14 22:33 UTC, vanessametonini requested changes

2021-07-14 22:33 UTC, vanessametonini commented on projeto/src/components/TimerView/index.tsx
Uma dúvida, será que é possível fazer o destructuring aqui para evitar a repetição e importar apenas as classes que vamos usar nesse componente? Caso positivo, acho que seria algo legal de fazer.

2021-07-14 22:33 UTC, vanessametonini commented on projeto/src/components/TimerView/index.tsx
> +      <span className={styles.timerNumero}>{secondUnits}</span>
daí ficaria apenas  `{timerNumero}`

2021-07-14 22:33 UTC, vanessametonini commented on projeto/src/components/Stopwatch/index.tsx
>  export function Stopwatch(props: IStopwatchProps){
O que acha e usar a notação com constantes e arrow function? Tenho visto com mais frequencia, além de garantir que o nome não vai tomado por ninguem (sim o JS deixa a gente reatribuir uma função :'{ ) 
 Ficaria algo como (usando já o retorno de react function components):
 
` export const StopWatch: React.FC<IStopWatchProps> = (props: StopWatchProps) => {`

2021-07-14 22:33 UTC, vanessametonini commented on projeto/src/pages/App.tsx
>      </div>
Também senti um pouco de dificuldade para entender o código pelos nomes dados as funções e variáveis, podemos parear e pensar juntas e aproveitar para colocar em portugues.

2021-07-21 12:59 UTC, bugan commented on projeto/src/common/utils/date.ts
> +export const delay = (ms = 1000) => new Promise((resolve, _) => {
Ficou melhor separa assim mesmo!

2021-07-21 12:59 UTC, bugan commented on projeto/src/pages/App.tsx
> +import { timeToSeconds } from 'common/utils/date'
traduzir

2021-07-22 12:18 UTC, merged